---
- hosts: all
  become: true
  tasks:

  - name: Create the default config file which is missing in bionic
    copy:
      dest: /etc/default/kubelet
      content: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

  - name: Configure node ip
    lineinfile:
      path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Copy the join command to server location
    copy: src=/tmp/join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh

  handlers:
    - name: docker status
      service: name=docker state=started

