# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE_NAME = "hashicorp/bionic64"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.name = "k8s-worker-base"
        v.memory = 2048
        v.cpus = 2
    end
      
    config.vm.define "k8s-worker-base" do |worker|
        worker.vm.box = IMAGE_NAME
        worker.vm.hostname = "k8s-worker-base"
        worker.vm.provision "ansible" do |ansible|
            ansible.playbook = "worker-base-playbook.yml"
        end
    end
end