# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE_NAME = "hashicorp/bionic64"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.name = "k8s-master-base"
        v.memory = 2048
        v.cpus = 2
    end
      
    config.vm.define "k8s-master-base" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.hostname = "k8s-master-base"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "master-base-playbook.yml"
        end
    end
end
